server:
  port: 10001
eureka:
  server:
    hostname: localhost
    port: 10000
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
spring:
  application:
    name: eureka-client-10001