server:
  port: 10003
eureka:
  instance:
    hostname: localhost
  client:
      service-url:
        defaultZone: http://localhost:10000/eureka/,http://localhost:10000/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          search-paths: /**
          uri: https://github.com/brilliantme007/config

